export const SELECT_CONTACT = 'SELECT_CONTACT';
export const REGISTER_MESSAGE = 'REGISTER_MESSAGE';
export const CONTACT_LOGIN = 'CONTACT_LOGIN';
export const SUBSCRIBED_CONTACTS = 'SUBSCRIBED_CONTACTS';
export const CONTACT_LOGOUT = 'CONTACT_LOGOUT';